FROM cgr.dev/45a0c61ea6fd977f050c5fb9ac06a69eed764595/go:1.24-dev AS builder

WORKDIR /app
COPY go.mod ./
COPY main.go ./
RUN go build -o /dummy-scanner .

FROM cgr.dev/chainguard/wolfi-base

COPY --from=builder /dummy-scanner /dummy-scanner
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

