name: Scan PR

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base

      - name: Run Dummy Scanner on base branch
        id: scan_base
        uses: erikaheidi/dummy-scanner@main
        with:
          directory: base

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: head

      - name: Run Dummy Scanner on PR branch
        uses: erikaheidi/dummy-scanner@main
        with:
          directory: head
          post_comment: 'true'
          base_count: ${{ steps.scan_base.outputs.total_files }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
